### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Kiwa21** [proto3/MAVkit#1]
Hi ! 
Just found out MAVKit. Very good job with this :)
Are there any known issues in the master branch ?

My goal is to add an handle message function in the MessengerInterfaces so I can have rules to redirect messages to certains listeners based on the msg id.

**Comment by Kiwa21** [comment]
Issue 1 : SIGPIPE issues not handled. For example, if Mavkit is using tcp_server and the client disconnect, the whole Mavkit process terminates.

**Comment by Kiwa21** [comment]
@proto3 Hello Lucas, can you help on managing a deconnection when using TCP Server so it can re-use the socket if a client reconnect later to the same port ?

The use of MSG_NOSIGNAL prevent the SIGPIPE to kill the whole process : 
bytes_sent = sendto(sock, buf, len, MSG_NOSIGNAL, (struct sockaddr*)&gcAddr, sizeof(struct sockaddr_in));

and using bytes_sent == -1 to know when it happened.

But I can't manage to cleanly close & re-open & listen for a new connection

Thanks.

and using

**Comment by proto3** [comment]
Hi @Kiwa21,
Sorry for the long delay, I've just fixed the connection loss problem with TCP. It will now reconnect automatically on both sides. Using MSG_NOSIGNAL was just fine.

I've also cleaned-up the CLI usage which was in progress from long time.

About the known issues, I'm pretty confident with the core architecture to transfer data. Just be careful when handling different versions of MAVlink and be aware that MAVkit has it's own heartbeat to force MAVlink 2.0 switching, otherwise it only receives 1.0 when logging messages passively.

Thanks your comments !
