### ISSUE TITLE
UDP client don't work

### ISSUE THREAD

**Issue by emialonzo** [proto3/MAVkit#5]
I'm using jmavsim/PX4 _INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14570 remote port 14550_

I wannna read the mavlinks messages with this command but nothing happens
**./mavkit --udp_client 192.168.1.10 14550 --display**

**Comment by proto3** [comment]
It's not clear on what is your setup here, I can't see what data are sent and from where. You may try to use --udp_server instead or try to connect on port 14570 or 14551. Otherwise the command syntax is correct.
If the problem persists, you can use Wireshark to ensure UDP packets are sent correctly. This would gave us more information to help you.
